db:
  build: database/
  dockerfile: database.dockerfile
  container_name: presenter-feedback-db
  environment:
    - MYSQL_ROOT_PASSWORD=pass
  #volumes:
    # database folder location
    # development
    # - ./database/storage:/var/lib/mysql

backend:
    build: .
    dockerfile: backend.dockerfile
    container_name: presenter-feedback-backend
    #environment:
    # - NODE_ENV=debug
    links:
      - db
    ports:
      - "8081:8081"
